import type { Locale } from "@/lib/i18n";

export const site = {
  name: "Idris Arif",
  arabicName: "إدريس عارف",
  url: "https://github.com/madarorbit/idris-portfolio",
  phone: "+967773076253",
  whatsapp: "https://wa.me/967773076253",
  instagram: "https://www.instagram.com/i_dr_is_m/?hl=ar",
  github: "https://github.com/madarorbit",
};

export const copy = {
  ar: {
    role: "المؤسس وباني المنتجات البرمجية والذكاء الاصطناعي",
    shortRole: "مؤسس · باني منتجات · برمجيات وذكاء اصطناعي",
    statement: "أبني منتجات برمجية لمشكلات حقيقية.",
    supporting: "أحوّل الفكرة إلى منتج يمكن استخدامه والبناء عليه.",
    viewWork: "استكشف الأعمال",
    contact: "تواصل معي",
    work: "الأعمال",
    about: "عن إدريس",
    contactNav: "تواصل",
    language: "English",
    selectedWork: "أعمال مختارة",
    selectedWorkIntro: "منتجات أعمل عليها من المشكلة إلى التجربة والنسخة المنشورة.",
    now: "الآن",
    nowText: "أركّز على بناء منتجات SaaS عملية، وعلى استخدام الذكاء الاصطناعي داخل سياق واضح يمكن الوثوق به.",
    aboutShort: "أبني منتجات تقنية لأن أفضل طريقة لفهم المشكلة هي الاقتراب منها، ثم تحويلها إلى تجربة واضحة تعمل فعلًا.",
    readCaseStudy: "اقرأ قصة المشروع",
    visit: "زيارة المنتج",
    explore: "استكشف التجربة",
    openTo: "منفتح على أحاديث حول",
    contactLead: "إذا كنت تبني شيئًا مفيدًا، يسعدني أن نتحدث.",
    phone: "اتصال",
    whatsapp: "واتساب",
    instagram: "إنستغرام",
    github: "GitHub",
    backToWork: "العودة إلى الأعمال",
    projectStatus: "الحالة",
    projectRole: "الدور",
    projectStack: "التقنيات",
    projectYear: "الفترة",
    current: "قيد البناء والتطوير",
    live: "منتج منشور",
    roleFounder: "المؤسس وباني المنتج",
    byline: "بُنيت من الفكرة إلى منتج قابل للاستخدام.",
    problem: "المشكلة",
    built: "ما الذي بُني",
    decisions: "قرارات المنتج والهندسة",
    experience: "التجربة الأساسية",
    status: "الوضع الحالي",
    links: "روابط",
    related: "مشروع آخر",
    noPage: "هذه الصفحة غير موجودة.",
    goHome: "العودة إلى البداية",
    footer: "منتجات حقيقية، وتعلّم مستمر، وبناء هادئ.",
  },
  en: {
    role: "Founder & builder of software products and AI systems",
    shortRole: "Builder · Founder · Software & AI",
    statement: "I build software products for real-world problems.",
    supporting: "Turning ideas into products people can use and build on.",
    viewWork: "View my work",
    contact: "Contact me",
    work: "Work",
    about: "About",
    contactNav: "Contact",
    language: "العربية",
    selectedWork: "Selected work",
    selectedWorkIntro: "Products I take from the problem to the experience and the shipped version.",
    now: "Now",
    nowText: "I am focused on practical SaaS products and on using AI inside clear, trustworthy product contexts.",
    aboutShort: "I build technology products because the best way to understand a problem is to get close to it, then turn it into a clear experience that works.",
    readCaseStudy: "Read the case study",
    visit: "Visit product",
    explore: "Explore the experience",
    openTo: "Open to conversations about",
    contactLead: "If you are building something useful, I would be glad to talk.",
    phone: "Phone",
    whatsapp: "WhatsApp",
    instagram: "Instagram",
    github: "GitHub",
    backToWork: "Back to work",
    projectStatus: "Status",
    projectRole: "Role",
    projectStack: "Stack",
    projectYear: "Period",
    current: "In active development",
    live: "Shipped product",
    roleFounder: "Founder & builder",
    byline: "Built from the idea into a product people can use.",
    problem: "The problem",
    built: "What I built",
    decisions: "Product & engineering decisions",
    experience: "Core experience",
    status: "Current status",
    links: "Links",
    related: "Another project",
    noPage: "This page does not exist.",
    goHome: "Back to home",
    footer: "Real products, continuous learning, and quiet building.",
  },
} satisfies Record<Locale, Record<string, string>>;

export type Copy = typeof copy.ar;
